before_install:
  - npm i -g npm@^5.7.0
language: node_js
node_js:
  - '11'
  - '10'
  - '8'

install:
  - npm ci

# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"
